[project]
org-name = "ballerina"
version = "@toml.version@"

[platform]
target = "java8"

    [[platform.libraries]]
        artifactId = "time"
        version = "@project.version@"
        path = "../time-native/build/libs/time-native-@project.version@.jar"
        groupId = "ballerina"
        modules = ["time"]
