[package]
org = "ballerina"
name = "time"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../time-native/build/libs/time-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "time"
version = "@project.version@"
