[package]
org = "ballerina"
name = "time"
version = "2.0.1"
authors = ["Ballerina"]
keywords = ["time", "utc", "epoch", "civil"]
repository = "https://github.com/ballerina-platform/module-ballerina-time"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/time-native-2.0.1-SNAPSHOT.jar"
version = "2.0.1-SNAPSHOT"
