[package]
org = "ballerina"
name = "time"
version = "@toml.version@"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/time-native-@project.version@.jar"
version = "@project.version@"
