[package]
org = "ballerina"
name = "time"
version = "2.0.1"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/time-native-2.0.1-SNAPSHOT.jar"
version = "2.0.1-SNAPSHOT"
